spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: pedido
          uri: lb://pedido
          predicates:
            - Path=/pedido/**
        - id: produto
          uri: lb://produto
          predicates:
            - Path=/produto/**
        - id: login
          uri: lb://login
          predicates:
            - Path=/usuario/**

server:
  port: ${PORTA:8080}
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka