server:
  port: 9000

spring:
  profiles:
    active: default
  cloud:
    config:
      enabled: false
  application:
    name: usuario


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultUrl: http://localhost:8761/eureka