server:
  port: 8080

spring:
  application:
    name: produto
  datasource:
    url: jdbc:mariadb://localhost:3307/marketplace
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultUrl: http://localhost:8761/eureka