server:
  port: 9010

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultUrl: http://localhost:8761/eureka
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true