server:
  port: 8888

spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoaoVitorMartinezM/configurations
          search-paths: pedido, produto, login
